### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by willmkt** [bhoriuchi/vue-graphql-rethink#3]
Hi, you could do a tutorial on how to build the projet, and how it works with vuex.

Thanks.

**Comment by bhoriuchi** [comment]
When you say build the project do you mean like from start to finish or just building it in webpack? 

As far as vuex, there are several tutorials out there including an official one http://vuex.vuejs.org/en/tutorial.html

At a high level, the project works like this

**Server**
there is a socket set up on the server that listens for `graphql.request` events and sends responses with a `graphql.response` event. The graphql queries are made by `graphql-factory`

reference code - https://github.com/bhoriuchi/vue-graphql-rethink/blob/master/lib/server/sockets.js

**vuex**
there is a vuex action called `graphql` that takes as its params, the client's socket, the schema to query, and the actual query itself

reference code - https://github.com/bhoriuchi/vue-graphql-rethink/blob/master/src/vuex/actions.js

you can see the `graphql` action sets up a once listener for the result and then emits the request. the result handler dispatches a vuex mutation to update the vuex store.

**Comment by willmkt** [comment]
It would be a start to finish tutorial, i'm begining in vue.js and graphql is getting very popular.

There is not a lot of material on vue.js graphql integrations, and i think it would be a plus for the community.

I have been looking at a project, http://www.apollostack.com, they integration for angular and react, but nothing for vue.js, in fact they are looking for someone to make the integration.

Thanks for the tips on the project.
